Updated
applibgroup/MultiStateView pull request #1
Opened 2021-12-14 03:37 UTC by Rahul1656

2021-12-15 15:58 UTC, samuel-abhishek commented on README.md
> +<img src="screenshots/ezgif.com-gif-maker (4).gif" width="500">
Please avoid spaces in the url path.

2021-12-15 16:00 UTC, samuel-abhishek commented on README.md
> +public void setViewState(int state) // Set the view state
when method prototypes are written, always end it with semicolon.

2021-12-15 16:04 UTC, samuel-abhishek commented on build.gradle
> +        source 'instalike/src/main/java'
Rename the source path from "instalike" to "multistateview"

2021-12-15 16:06 UTC, samuel-abhishek commented on entry/src/main/java/me/xdj/multistateview/ActivityUtils.java
> +/*
Remove the applibgroup copyright for this file. It is the same as Base library's ActivityUtils.java

2021-12-15 16:08 UTC, samuel-abhishek commented on entry/src/main/java/me/xdj/multistateview/MultiStateFragment.java
> +/*
Remove the applibgroup copyright for this file too

2021-12-15 16:09 UTC, samuel-abhishek commented on entry/src/ohosTest/java/me/xdj/multistateview/ExampleOhosTest.java
> +package me.xdj.multistateview;
Can add the applibgroup copyright for all the test files which are developed

2021-12-15 16:17 UTC, samuel-abhishek commented on multistateview/src/main/java/me/xdj/view/MultiStateView.java
> +        if (view == null && mCurrentState != STATE_CONTENT) {
All scenarios are not handled here. 
Check this scenario : When "view" is null and also mCurrentState is equal to STATE_CONTENT - this scenario is not handled in this code

2021-12-15 16:24 UTC, samuel-abhishek commented on multistateview/src/main/java/me/xdj/view/SimpleMultiStateView.java
> +        String emptyViewString = attrs.getAttr("msv_emptyView").get().getStringValue();
replace emptyViewString, emptyViewString1, emptyViewString2 variable names with meaningful ones. You can retain the variables naming convention from the base library.

2021-12-15 16:27 UTC, samuel-abhishek commented on multistateview/src/main/java/me/xdj/view/SimpleMultiStateView.java
> +        if (emptyId != -1) {
retain the base library's variable naming for emptyId variable.

2021-12-15 16:29 UTC, samuel-abhishek requested changes
Please check and handle the review comments. Also, please test all the public functions exposed by this library along with the custom attributes.

2021-12-17 11:04 UTC, samuel-abhishek commented on build.gradle
> +        classpath 'com.huawei.ohos:hap:2.4.4.2'
why change this ? Need 3.0.3.4 & 1.2.6.0 classpath for sdk6

2021-12-17 11:36 UTC, samuel-abhishek commented on multistateview/src/main/java/com/hmos/compat/utils/AttrUtils.java
> +    public static Integer utils(AttrSet attrs) {
utis1, utils2, utils3 is still duplication code. Have only one method and pass attr key as parameter.

2021-12-17 12:07 UTC, samuel-abhishek commented on multistateview/src/main/java/me/xdj/view/MultiStateView.java
> +            Logger.getLogger("Content is null");
if (view == null && mCurrentState == STATE_CONTENT) -- the code flow continues inspite of encountering a null condition. In ideal case, the flow must terminate here. Please check & understand the base library implementation

2021-12-17 12:09 UTC, samuel-abhishek requested changes
Please check and handle the comments

2021-12-20 06:51 UTC, samuel-abhishek approved these changes
okay

2021-12-20 07:09 UTC, superlib-framework commented on entry/src/main/java/me/xdj/multistateview/MainAbility.java
> +    MultiStateFragment mContentFragment;
Please change class name to MultiStateFraction

2021-12-20 07:12 UTC, superlib-framework commented on entry/src/main/resources/base/element/string.json
> +      "name": "mainability_HelloWorld",
remove unnecessary strings, other string values also please add value related to library

2021-12-20 08:35 UTC, superlib-framework commented on entry/src/main/resources/en/element/string.json
> +      "name": "mainability_HelloWorld",
Update the strings based on main file

2021-12-20 08:36 UTC, superlib-framework commented on entry/src/ohosTest/java/me/xdj/multistateview/ExampleOhosTest.java
> +        MultiStateView multiStateView=new MultiStateView(context);
format the code

2021-12-20 08:38 UTC, superlib-framework commented on multistateview/src/main/java/com/hmos/compat/utils/AttrUtils.java
> + * @author a00237416.
Please remove the author and since details.

2021-12-20 08:41 UTC, superlib-framework commented on multistateview/src/main/java/me/xdj/view/MultiStateView.java
> +    public void addViewForStatus(int status, int resLayoutId) {
add javadoc to public methods, if need not be declared as public, then make it private

2021-12-20 08:42 UTC, superlib-framework commented on multistateview/src/main/java/me/xdj/view/MultiStateView.java
> +    public void postDelayed(Runnable loadingHide, int minDelay) {
make it private, all such locally used apis update to private

2021-12-21 05:06 UTC, superlib-framework commented
ok

2021-12-21 05:48 UTC, sharathks84 approved these changes
OK, approved

2021-12-21 05:58 UTC, Gleelakrishna approved these changes
ok

2021-12-21 05:58 UTC, merged